from_latest_tag = false
ignore_merge_commits = true
ignore_fixup_commits = true
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = [
  "./scripts/update_project_version.sh {{version}}",
  "./scripts/increment_export_codes.sh"
]
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]
hotfix = { changelog_title = "🪲 Bug fixes" }
fix = { changelog_title = "🪲 Bug fixes" }
feat = { changelog_title = "➕ New features" }
chore = { changelog_title = "", omit_from_changelog = true }
ci = { changelog_title = "", omit_from_changelog = true }
perf = { changelog_title = "", omit_from_changelog = true }
test = { changelog_title = "", omit_from_changelog = true }
refactor = { changelog_title = "", omit_from_changelog = true }
refacto = { changelog_title = "", omit_from_changelog = true }
build = { changelog_title = "", omit_from_changelog = true }


[changelog]
path = "CHANGELOG.md"
template = "scripts/changelog.template"
authors = []

[bump_profiles]

[packages]